### ISSUE TITLE
about L2 norm in Simple HGN and a problem about the submission website

### ISSUE THREAD

**Issue by SsrCode** [THUDM/HGB#12]
Thanks for your team's good work. But I have a doubt about the last L2 norm trick used in Simple HGN. From the paper's ablation study, we can see that the performance of Simple HGN drops greatly without last L2 norm trick(even decrease 5-8% , it seems that the high performance of Simple HGN comes from this trick), which is quite strange. 

Also, the website https://www.biendata.xyz/competition/hgb-1 has a problem recently. When I make a submission, the website will stop at  "evaluating" for quite a long time and won't return the results. Can you check it? Thank you

**Comment by vedantbhatia** [comment]
How long should evaluation take? Can I submit files only for 1 dataset?
