### ISSUE TITLE
链接预测评测界面卡住无结果返回

### ISSUE THREAD

**Issue by SpaceLearner** [THUDM/HGB#14]
您好，最近在提交链接预测的结果时，系统会一直显示加载的进度条，但是没有任何反馈结果，请问是否是评测系统出现问题？

**Comment by 1049451037** [comment]
您好，请确认提交的文件格式与baseline代码的输出格式相同，我这边测试的提交是可以正常评测的。

**Comment by SpaceLearner** [comment]
您好，已经重新clone了本repo两次，数据集重新下载两次，并且用baseline代码run后提交，还是一直卡在评估界面没有返回。节点分类没有遇到这个问题。

**Comment by 1049451037** [comment]
感谢反馈，正在排查原因，对您造成的不便还请谅解！

**Comment by 1049451037** [comment]
@SpaceLearner 问题已经解决，我这边可以正常提交了，您试一下是否可以，如果有问题再反馈～

**Comment by SpaceLearner** [comment]
感谢及时的回复和解决～



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Qingsong Lv ***@***.***&gt;
发送时间: 2021年12月23日 19:01
收件人: THUDM/HGB ***@***.***&gt;
抄送: NLNR ***@***.***&gt;, Mention ***@***.***&gt;
主题: Re: [THUDM/HGB] 链接预测评测界面卡住无结果返回 (Issue #14)





 
@SpaceLearner 问题已经解决，我这边可以正常提交了，您试一下是否可以，如果有问题再反馈～
