### ISSUE TITLE
上传HGB失败

### ISSUE THREAD

**Issue by yijicheng** [THUDM/HGB#24]
您好，我使用baseline的代码生成文件，并压缩上传，出现这个报错，请问是什么原因？
![image](https://user-images.githubusercontent.com/53086386/163537858-efd00f01-8618-4c53-8e7f-b6cca6656762.png)
![image](https://user-images.githubusercontent.com/53086386/163537886-12df9c56-55ee-4301-9e2d-24887e398e96.png)

**Comment by 1049451037** [comment]
您好，可以参考[FAQ](https://github.com/THUDM/HGB#faq)的question 4。
