### ISSUE TITLE
数据文件问题

### ISSUE THREAD

**Issue by shoyua** [THUDM/HGB#30]
请问结点分类任务中label.dat.test和label.dat.test_full两个文件的区别？是label.dat.test_full这个文件中的label是随机替换的，label.dat.test文件label是真实的，可以这样理解吗？

**Comment by 1049451037** [comment]
是的，full是随机替换的但是是完整的测试集，label.dat.test是真实的但是不完整。

**Comment by shoyua** [comment]
好的，多谢解答
