### ISSUE TITLE
节点分类任务提交页面卡住

### ISSUE THREAD

**Issue by GooLiang** [THUDM/HGB#31]
您好，最近在提交节点分类任务的结果时，系统会一直显示加载的进度条，但是没有任何反馈结果。文件格式没有问题，之前上传都可以出结果，近两天出现的问题。

**Comment by 1049451037** [comment]
Hi, we have made test set public. You can refer to the latest readme of HGB repo and get your metrics locally.

**Comment by ShuaiWang97** [comment]
> Hi, we have made test set public. You can refer to the latest readme of HGB repo and get your metrics locally.

Thanks for the prompt response! Do you mean the `label.dat.test_full` in each dataset folder is the real test set now?  From issue #30, It seems  `label.dat.test_full` was random labels before.
Thanks again for the help!

**Comment by 1049451037** [comment]
In this public data, there is no `label.dat.test_full` anymore. The `label.dat.test` contains full test set and real labels.

**Comment by ShuaiWang97** [comment]
I see. Thanks a lot for the help!
