### ISSUE TITLE
测试集的数据仍未公开

### ISSUE THREAD

**Issue by hcmdgh** [THUDM/HGB#32]
您好，您提到已公开测试集的数据，但是从网盘链接来看，这些文件的更新时间仍为1年前，似乎并没有公开新的数据？

**Comment by hcmdgh** [comment]
链接如下：
Node Classification: https://cloud.tsinghua.edu.cn/d/a2728e52cd4943efa389/
Link Prediction: https://cloud.tsinghua.edu.cn/d/10974f42a5ab46b99b88/

**Comment by 1049451037** [comment]
您好，文件是一年前就存在的，只是链接刚公开，里面有完整的测试集数据。

**Comment by hcmdgh** [comment]
Thanks a lot.
