### ISSUE TITLE
URLs are invaild for all datasets 

### ISSUE THREAD

**Issue by fengxyStar** [THUDM/HGB#35]
Hi, I found that all datasets provided on the HGB website are invalid. I clicked "Download" but the new page shows that "Sorry, but the requested page could not be found".

**Comment by 1049451037** [comment]
Yes, Tsinghua cloud urls are invalid now because I have graduated... You can use the alternative google drive urls, which are also in readme.

**Comment by fengxyStar** [comment]
> Yes, Tsinghua cloud urls are invalid now because I have graduated... You can use the alternative google drive urls, which are also in readme.
Thank you so much!

**Comment by fengxyStar** [comment]
Thank you so much for your help. I've successfully downloaded these
datasets.

Qingsong Lv ***@***.***> 于2023年7月20日周四 15:36写道：
