### ISSUE TITLE
Dataset about IMDB

### ISSUE THREAD

**Issue by Theheavens** [THUDM/HGB#4]
Dataset IMDB has multi labels. But I am wondering how to save the file for evaluation, cause I don't see it in [run_multi.py](https://github.com/THUDM/HGB/blob/master/NC/benchmark/methods/GNN/run_multi.py). And else, I want to know what API in sklearn to evaluate multi-label.

**Comment by Theheavens** [comment]
info.dat in IMDB, #L8160 "meaning" maybe is 'movie->actor'. 
info.dat in ACM, the 'Attribute Dimension' of author is not zero, right?

**Comment by 1049451037** [comment]
You can see here for reference to generate prediction file for IMDB: https://github.com/THUDM/HGB/blob/master/NC/benchmark/methods/baseline/run_multi.py#L151

**Comment by 1049451037** [comment]
Yes, #L8160 is 'movie->actor'. It is a typo. The info.dat files contain some information that we haven't used so far. To load data and check the attribute dimension, you can use our [data_loader](https://github.com/THUDM/HGB/blob/master/NC/benchmark/scripts/data_loader.py). Detailed document is on the way... You can see the code in [baseline](https://github.com/THUDM/HGB/tree/master/NC/benchmark/methods/baseline) folder as example to use. Sorry for the inconvenience.
