### ISSUE TITLE
关于gtn-acm数据集的边个数问题

### ISSUE THREAD

**Issue by Sangs3112** [THUDM/HGB#41]
您好，我运行了SimpleHGN的代码以后发现，在gtn-acm数据集中，edge_index的维度是[2, 25922]，表明其中存在25922条边。但是在代码的build_g_feat(self, A)函数中，使用的是data.adj，而非data.edge_index。而通过data.adj生成的edges中竟然存在34916条边，我不知道为什么数据集的一张图的邻接矩阵adj和edge_index中的边数不一样，也不清楚这些差距在哪里。
如果您知道的话可以告诉我吗，这对我很重要！感谢。

**Comment by 1049451037** [comment]
self-loops are added to adj.

**Comment by Sangs3112** [comment]
好吧，我理解了。原来这样，非常感谢！
