### ISSUE TITLE
关于NC/benchmark/methods/RSHN/data的数据下载链接失效

### ISSUE THREAD

**Issue by GooLiang** [THUDM/HGB#56]
您好，我想要测试RSHN中的三个NC数据集（ACM, DBLP, IMDB），但是Read.me中给的链接已经失效。可以麻烦您提供可下载的链接么

**Comment by 1049451037** [comment]
所有链接应该都有清华云盘和google drive两份，清华云盘因为我毕业了所以失效了，只能用google drive了。

**Comment by GooLiang** [comment]
google drive也只是提供了三个link预测的数据集，并没有提供NC预测的数据集（ACM, DBLP, IMDB）

**Comment by 1049451037** [comment]
NC数据集需要到NC目录里：https://github.com/THUDM/HGB/tree/master/NC

**Comment by 1049451037** [comment]
如果你说的是HGB benchmark数据集，就需要到benchmark目录里：https://github.com/THUDM/HGB/tree/master/NC/benchmark/methods/RSHN

**Comment by GooLiang** [comment]
您好，我就是在NC目录里找的。但是只有
<img width="943" alt="微信图片_20240125104657" src="https://github.com/THUDM/HGB/assets/34645017/619959bd-f6b3-4b13-a08a-518b0b8446c2">
这是RSHN在link预测用到的数据集。我想要的是node classification中的ACM, DBLP, IMDB数据集

**Comment by 1049451037** [comment]
那就在主页的readme里：https://github.com/THUDM/HGB

**Comment by GooLiang** [comment]
您是说这个链接么Node Classification: https://drive.google.com/drive/folders/10-pf2ADCjq_kpJKFHHLHxr_czNNCJ3aX?usp=sharing
这个链接提供的也是用于HGB这类的节点分类数据集格式。RSHN需要的是这类格式才可以
def load_rel_graph(name):
    name = name
    x_path = '/HGB/NC/benchmark/methods/RSHN/data/data/' + name + '-relation/rel_graph_x.npy'
    edge_index_path = '/HGB/NC/benchmark/methods/RSHN/data/data/' + name + '-relation/rel_graph_edge_index.npy'
    edge_attr_path = '/HGB/NC/benchmark/methods/RSHN/data/data/' + name + '-relation/rel_graph_edge_attr.npy'

**Comment by 1049451037** [comment]
RSHN是一篇链接预测的论文，原文并没有节点分类，所以没有对应的数据集。

**Comment by 1049451037** [comment]
那就是这个：

> 如果你说的是HGB benchmark数据集，就需要到benchmark目录里：https://github.com/THUDM/HGB/tree/master/NC/benchmark/methods/RSHN

RSHN原文并没有评测ACM、DBLP、IMDB，要评测这几个数据集就要用我们这个代码。我们修改了RSHN的数据加载代码以支持我们的数据格式。

**Comment by GooLiang** [comment]
抱歉，我的疏忽。我再检查代码时发现RSHN的关系数据加载是需要运行代码之后再生成的。问题解决了，感谢您的及时回复
