### ISSUE TITLE
HGT在IMDB的结果比较差

### ISSUE THREAD

**Issue by cold-rivers** [THUDM/HGB#61]
[train_hgt.py](https://github.com/THUDM/HGB/blob/master/NC/benchmark/methods/HGT/train_hgt.py) 运行IMDB会报错，我根据HAN和SimpleHGN的代码修改了一下之后可以正常训练，但是表现只有{'micro-f1': 0.5835903763109191, 'macro-f1': 0.5462626259882535}，和论文差别太大了，请问是否有一个hgt_multi的代码吗

**Comment by 1049451037** [comment]
https://github.com/THUDM/HGB/tree/master/NC/benchmark/methods/HGT

**Comment by cold-rivers** [comment]
sh run_imdb.sh
0 {}
1 {'0': 4932}
2 {'0': 4932, '1': 2393}
3 {'0': 4932, '1': 2393, '2': 6124}
1097 3202 274
Traceback (most recent call last):
  File "/home/HGB_master/NC/benchmark/methods/HGT/train_hgt.py", line 148, in <module>
    train_loss = F.cross_entropy(logits[train_idx], labels[train_idx].to(device))
  File "/home/miniconda3/envs/dgl/lib/python3.9/site-packages/torch/nn/functional.py", line 3026, in cross_entropy
    return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index, label_smoothing)
RuntimeError: 0D or 1D target tensor expected, multi-target not supported
直接运行shell会出现这个错误，所以我把loss改成了loss = nn.BCELoss()
而且在train_hgt.py的147行添加了pred =torch.sigmoid(logits)，就会出现结果较差的问题

**Comment by cold-rivers** [comment]
HAN和SimpleHGN的结果和论文中都是偏差不大，只有HGT不太行

**Comment by 1049451037** [comment]
感谢反馈，@wzfhaha 可以帮忙看一下这个问题吗？

**Comment by cold-rivers** [comment]
我已经解决了，非常感谢
